[package]
name = "common-exception"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
common-arrow = { path = "../arrow" }

anyhow = "1.0.51"
backtrace = "0.3.63"
octocrab = "0.15.1"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.72"
thiserror = "1.0.30"
tonic = "0.6.1"
prost = "0.9.0"
paste = "1.0.6"
sled = { git = "https://github.com/datafuse-extras/sled", tag = "v0.34.7-datafuse.1",default-features = false }

# Github dependencies
sqlparser = { git = "https://github.com/datafuse-extras/sqlparser-rs", rev = "18dc375" }
