[package]
name = "databend-query"
version = "0.1.0"
description = "A real-time Cloud Distributed Query Engine"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[[bin]]
name = "databend-query"
path = "src/bin/databend-query.rs"

[[bin]]
name = "databend-benchmark"
path = "src/bin/databend-benchmark.rs"

[features]
default = ["simd"]
simd = ["common-arrow/simd"]

[dependencies]
# Workspace dependencies
common-arrow = { path = "../common/arrow" }
common-base = { path = "../common/base" }
common-clickhouse-srv = { path = "../common/clickhouse-srv" }
common-dal = { path = "../common/dal" }
common-datablocks = { path = "../common/datablocks" }
common-datavalues = { path = "../common/datavalues" }
common-exception = { path = "../common/exception" }
common-flight-rpc = { path = "../common/flight-rpc" }
common-functions = { path = "../common/functions" }
common-infallible = { path = "../common/infallible" }
common-io = { path = "../common/io" }
common-management = { path = "../common/management" }
common-mem-allocator = { path = "../common/mem-allocator" }
common-meta-api = { path = "../common/meta/api" }
common-meta-embedded = { path = "../common/meta/embedded" }
common-meta-flight = { path = "../common/meta/flight" }
common-meta-sled-store = { path = "../common/meta/sled-store" }
common-meta-types = { path = "../common/meta/types" }
common-macros = { path = "../common/macros" }
common-metrics = { path = "../common/metrics" }
common-planners = { path = "../common/planners" }
common-streams = { path = "../common/streams" }
common-tracing = { path = "../common/tracing" }

# Github dependencies
clickhouse-rs = { git = "https://github.com/datafuse-extras/clickhouse-rs", rev = "fe0406b" }
msql-srv = { git = "https://github.com/datafuse-extras/msql-srv", rev = "e4c8f3d" }
sqlparser = { git = "https://github.com/datafuse-extras/sqlparser-rs", rev = "b42ff01" }

# Crates.io dependencies
ahash = "0.7.6"
async-compat = "0.2.1"
async-trait = "0.1.52"
async-stream = "0.3.2"
poem = { version = "1.0.38", features = ["rustls", "multipart"] }
bumpalo = "3.8.0"
byteorder = "1.4.3"
bytes = "1.1.0"
cargo-license = "0.4.2"
cargo_metadata = "0.14.1"
chrono = "0.4.19"
chrono-tz = "0.6.1"
crossbeam = "0.8.1"
crossbeam-queue = "0.3.2"
ctrlc = { version = "3.2.1", features = ["termination"] }
dyn-clone = "1.0.4"
futures = "0.3.18"
headers = "0.3.5"
hyper = "0.14.16"
indexmap = "1.7.0"
lazy_static = "1.4.0"
maplit = "1.0.2"
metrics = "0.17.0"
nom = "7.1.0"
num = "0.4.0"
num_cpus = "1.13.0"
octocrab = "0.15.1"
paste = "1.0.6"
prost = "0.9.0"
quantiles = "0.7.1"
rand = "0.8.4"
reqwest = "0.11.7"
serde = { version = "1.0.131", features = ["derive"] }
serde_json = "1.0.72"
sha1 = "0.6.0"
sha2 = "0.10.0"
structopt = "0.3.25"
structopt-toml = "0.5.0"
threadpool = "1.8.1"
tokio-rustls = "0.23.1"
tokio-stream = { version = "0.1.8", features = ["net"] }
toml = "0.5.8"
tonic = "0.6.2"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
walkdir = "2.3.2"
parquet-format-async-temp= "0.2.0"

[dev-dependencies]
criterion = "0.3.5"
flaky_test = "0.1.0"
mysql = "21.0.2"
pretty_assertions = "1.0.0"
reqwest = { version = "0.11.7", features = ["json", "native-tls"] }
tempfile = "3.2.0"
float-cmp = "0.9.0"

[build-dependencies]
common-building = { path = "../common/building" }

[[bench]]
name = "bench_main"
harness = false
