[package]
name = "databend-meta"
version = "0.1.0"
description = "distributed meta data service"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[[bin]]
name = "databend-meta"
path = "src/bin/metasrv.rs"

[features]
default = ["simd"]
simd = ["common-arrow/simd"]

[dependencies]
# Workspace dependencies
common-arrow = {path = "../common/arrow"}
common-datavalues = {path = "../common/datavalues"}
common-exception = { path = "../common/exception" }
common-flight-rpc = { path = "../common/flight-rpc" }
common-infallible = { path = "../common/infallible" }
common-base = { path = "../common/base" }
common-meta-api = { path = "../common/meta/api" }
common-meta-flight = { path = "../common/meta/flight" }
common-meta-raft-store = { path = "../common/meta/raft-store" }
common-meta-sled-store = { path = "../common/meta/sled-store" }
common-meta-types = { path = "../common/meta/types" }
common-tracing = { path = "../common/tracing" }
common-macros = { path = "../common/macros" }
common-metrics = { path = "../common/metrics" }

# Github dependencies

# Crates.io dependencies
anyhow = "1.0.51"
async-raft = { git = "https://github.com/datafuse-extras/async-raft", tag = "v0.6.2-alpha.14.1" }
async-trait = "0.1.51"
backtrace = "0.3.63"
byteorder = "1.4.3"
derive_more = "0.99.17"
futures = "0.3.18"
indexmap = "1.7.0"
lazy_static = "1.4.0"
maplit = "1.0.2"
metrics = "0.17.0"
metrics-exporter-prometheus = "0.6.1"
num = "0.4.0"
num_cpus = "1.13.0"
prost = "0.9.0"
rand = "0.8.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.72"
sled = { git = "https://github.com/datafuse-extras/sled", tag = "v0.34.7-datafuse.1",default-features = false }
structopt = "0.3.25"
structopt-toml = "0.5.0"
tempfile = "3.2.0"
thiserror = "1.0.30"
threadpool = "1.8.1"
tokio-stream = "0.1.8"
tonic = { version = "0.6.1", features = ["tls"] }

sha2 = "0.9.8"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
poem = { version = "1.0.32", features = ["rustls"] }

[dev-dependencies]
common-meta-api = {path = "../common/meta/api" }

pretty_assertions = "1.0.0"
test-env-log = "0.2.8"
flaky_test = "0.1.0"
reqwest = { version = "0.11.6", features = ["json"] }

[build-dependencies]
common-building = {path = "../common/building"}
tonic-build = "0.6.0"
