[package]
name = "common-flight-rpc"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = {path = "../arrow"}
common-base = {path = "../base" }
common-exception= {path = "../exception"}
common-tracing = {path = "../tracing" }

# Github dependencies

# Crates.io dependencies
futures = "0.3.18"
jwt-simple = "0.10.7"
prost = "0.9.0"
serde = { version = "1.0.131", features = ["derive"] }
serde_json = "1.0.72"
tokio-stream = "0.1.8"
tonic = { version = "0.6.2", features = ["transport", "codegen", "prost", "tls-roots", "tls"] }
hyper = "0.14.16"
lazy_static = "1.4.0"
trust-dns-resolver = { version = "0.20.3", features = ["system-config"] }
async-trait = "0.1.52"

[dev-dependencies]
pretty_assertions = "1.0.0"

[build-dependencies]

[features]
mocks = []
